


name: Déploiement de l'application Dash

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Extraire le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.1'

      # Étape 3 : Installer les dépendances
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Configurer les variables d'environnement
      - name: Configurer le token GitHub
        run: echo "GITHUB_TOKEN=${{ secrets.GITTHUB }}" >> $GITHUB_ENV

      # Étape 5 : Lancer l'application
      - name: Lancer l'application
        run: |
         # Récupérer la clé API GitHub depuis les variables d'environnement
          export GITHUB_API_KEY=$GITTHUB
          
          python gen.py
