name: Mon Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout du code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances Python
      - name: Installer les dépendances
        run: pip install -r requirements.txt

      # Étape 4 : Injecter le secret dans l'environnement
      - name: Définir le mot de passe comme variable d'environnement
        run: echo "MOTDEPASSE=${{ secrets.MOTDEPASSE }}" >> $GITHUB_ENV

      # Étape 5 : Exécuter le script Python
      - name: Exécuter le script Python
        run: python VisGenealogLoc.py
